spring.application.name=demo1

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/taskdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info

management.endpoint.health.show-details=always

server.port=${PORT:8080}